
Start training...
Epoch: 1/150
Traceback (most recent call last):
  File "/opt/ml/level1_segmentation-cv-13/main.py", line 128, in <module>
    run(args)
  File "/opt/ml/level1_segmentation-cv-13/main.py", line 98, in run
    fit(model        = model,
  File "/opt/ml/level1_segmentation-cv-13/train.py", line 163, in fit
    train_metrics = train(model,accelerator, trainloader, criterion, optimizer, log_interval, args)
  File "/opt/ml/level1_segmentation-cv-13/train.py", line 67, in train
    for idx, (images, masks) in tqdm(enumerate(dataloader),total=len(dataloader)):
TypeError: 'module' object is not callable